# Generated by Django 4.1.1 on 2024-01-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotes', models.TextField()),
                ('author', models.TextField(max_length=100)),
                ('show', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='postingan',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
