# Generated by Django 4.1.1 on 2024-01-16 02:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0002_quotes_alter_postingan_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='konten',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
