# Generated by Django 4.1.1 on 2024-01-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
