# Generated by Django 4.1.1 on 2024-01-19 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postingan', '0005_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingan',
            name='like',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
