# Generated by Django 4.1.1 on 2024-01-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0006_postingan_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='komentar',
            options={'verbose_name_plural': 'Komentar'},
        ),
        migrations.AlterModelOptions(
            name='postingan',
            options={'verbose_name_plural': 'Postingan'},
        ),
        migrations.AlterField(
            model_name='quotes',
            name='show',
            field=models.BooleanField(unique=True),
        ),
    ]
