# Generated by Django 4.1.1 on 2024-01-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postingan', '0007_alter_komentar_options_alter_postingan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='show',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
