# Generated by Django 4.1.1 on 2024-01-25 22:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postingan', '0008_alter_quotes_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name_plural': 'Quote'},
        ),
        migrations.AlterField(
            model_name='postingan',
            name='like',
            field=models.ManyToManyField(null=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
