# Generated by Django 4.1.1 on 2024-01-25 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postingan', '0009_alter_quotes_options_alter_postingan_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
