# Generated by Django 4.1.1 on 2024-01-26 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postingan', '0010_alter_postingan_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingan',
            name='like',
            field=models.ManyToManyField(related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
