# Generated by Django 4.1.1 on 2024-01-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VerificationUser',
        ),
    ]
