# Generated by Django 4.1.1 on 2024-01-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/assets/profile.jpg', null=True, upload_to='static/profile_pictures/'),
        ),
    ]
