# Generated by Django 4.1.1 on 2024-01-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification',
        ),
    ]
